default_device: "cuda" # "cpu" or "cuda"
save_results: true
results_dir: "results/"
random_seed: 42
log_level: "INFO"

# Model parameters
max_length: 128
batch_size: 8
weight_decay: 0.01
epochs: 3

# Evaluation parameters
max_eval_samples: 100
human_eval_model: "mixtral-8x7b-instruct" #"llama3-70b-instruct"
