default_device: "cuda" # "cpu" or "cuda"
save_results: true
results_dir: "results/"

# Model parameters
max_length: 128
batch_size: 8
weight_decay: 0.01
epochs: 3

# Evaluation parameters
max_eval_samples: 150
human_eval_model: "meta-llama/llama-4-scout-17b-16e-instruct"
