default_device: "cpu" # or "cuda"
save_results: true
results_dir: "results/"
random_seed: 42
log_level: "INFO"

# Model parameters
max_length: 128
batch_size: 4 #16
num_epochs: 5
learning_rate: 5e-5
weight_decay: 0.01

# Evaluation parameters
max_eval_samples: 100 #500
max_new_tokens: 128
human_eval_model: "deepseek-r1-distill-llama-70b"
