default_device: "cuda" # "cpu" or "cuda"
save_results: true
results_dir: "results/"
random_seed: 42
log_level: "INFO"

# Model parameters
max_length: 128
batch_size: 16
weight_decay: 0.01
epochs: 5

# Evaluation parameters
max_eval_samples: 10 #500
human_eval_model: "deepseek-r1-distill-llama-70b"
