datasets:
  bitext: 
    name: "bitext/Bitext-customer-support-llm-chatbot-training-dataset"
    split: "train"
    fields:
      input: "instruction"
      output: "response"
      intent: "intent"
    sample_frac: 0.01 # original size: 26,872, new size 0.2s: 5374.4
    test_size: 0.2

  customer_service:
    name: "pranav301102/customer-service-for-llm"
    split: "train"
    fields:
      input: "instruction"
      output: "response"
      intent: "intent"
    sample_frac: 1 # size: 2,700
    test_size: 0.2
