datasets:
  bitext:
    name: "bitext/Bitext-customer-support-llm-chatbot-training-dataset"
    split: "train"
    fields:
      input: "instruction"
      output: "response"
    sample_frac: 0.2  # Use 20% of data for faster experimentation
    test_size: 0.2    # 20% for testing

  bitod:
    name: "pranav301102/customer-service-for-llm"
    split: "train"
    fields:
      input: "instruction"
      output: "response"
      intent: "intent"
    sample_frac: 0.2
    test_size: 0.2 