datasets:
  bitext:
    name: "bitext/Bitext-customer-support-llm-chatbot-training-dataset"
    split: "train"
    fields:
      input: "instruction"
      output: "response"
      intent: "intent"
    sample_frac: 0.1 # 2,687 samples
    test_size: 0.2

  customer_service:
    name: "pranav301102/customer-service-for-llm"
    split: "train"
    fields:
      input: "instruction"
      output: "response"
      intent: "intent"
    sample_frac: 1 # 2,700 samples
    test_size: 0.2
