settings:
  available_datasets: ["bitext", "customer_service"]

experiments:
  - name: "two_step_baseline"
    type: "two_step"
    intent_model: "ground_truth"
    response_model: "t5-base"
    description: "Two-step model using ground-truth intents and a pretrained T5-base model for response generation."
    requirements:
      needs_intent: true

  - name: "single_step_pretrained"
    type: "single_step"
    response_model: "t5-base"
    description: "Single-step response generation using a pretrained T5-base model."
    requirements:
      needs_intent: false

  - name: "single_step_ft"
    type: "single_step"
    response_model: "t5-finetuned"
    description: "Single-step response generation using a fine-tuned T5 model."
    requirements:
      needs_intent: false

  - name: "two_step_pretrained"
    type: "two_step"
    intent_model: "t5-base"
    response_model: "t5-base"
    description: "Two-step model using pretrained T5-base for both intent detection and response generation."
    requirements:
      needs_intent: true

  - name: "two_step_partial_ft"
    type: "two_step"
    intent_model: "bert-finetuned"
    response_model: "t5-base"
    description: "Two-step model with fine-tuned BERT for intent detection and pretrained T5-base for response generation."
    requirements:
      needs_intent: true

  - name: "two_step_complete_ft"
    type: "two_step"
    intent_model: "bert-finetuned"
    response_model: "t5-finetuned"
    description: "Two-step model with fine-tuned BERT for intent detection and fine-tuned T5 for response generation."
    requirements:
      needs_intent: true

  - name: "two_step_partial_ft_TMP"
    type: "two_step"
    intent_model: "t5-base"
    response_model: "t5-finetuned"
    description: "TMP"
    requirements:
      needs_intent: true
