# Global experiment settings
settings:
  available_datasets: ["bitext", "bitod"]  # List of datasets that can be used with any experiment

experiments:
  # Two-step baseline (Ground Truth Intent + Pretrained GPT-4)
  - name: "two_step_baseline"
    type: "two_step"
    intent_model: "ground_truth"
    response_model: "gpt-4"
    description: "Ground Truth Intent + Pretrained GPT-4"
    requirements:
      needs_intent: true

  # Single-step pretrained (Direct GPT-4)
  - name: "single_step_pretrained"
    type: "single_step"
    response_model: "gpt-4"
    description: "Direct Response Generation with Pretrained GPT-4"
    requirements:
      needs_intent: false

  # Single-step Fine-tuned (Fine-tuned T5)
  - name: "single_step_ft"
    type: "single_step"
    response_model: "t5-finetuned"
    description: "Direct Response Generation with Fine-tuned T5"
    requirements:
      needs_intent: false

  # Two-step pretrained (GPT-4 Intent + GPT-4 Response)
  - name: "two_step_pretrained"
    type: "two_step"
    intent_model: "gpt-4"
    response_model: "gpt-4"
    description: "Pretrained GPT-4 for both Intent and Response"
    requirements:
      needs_intent: true

  # Two-step partial Fine-tuned (Fine-tuned BERT + GPT-4)
  - name: "two_step_partial_ft"
    type: "two_step"
    intent_model: "bert-finetuned"
    response_model: "gpt-4"
    description: "Fine-tuned BERT for Intent + Pretrained GPT-4 for Response"
    requirements:
      needs_intent: true

  # Two-step complete Fine-tuned (Fine-tuned BERT + Fine-tuned T5)
  - name: "two_step_complete_ft"
    type: "two_step"
    intent_model: "bert-finetuned"
    response_model: "t5-finetuned"
    description: "Fine-tuned BERT for Intent + Fine-tuned T5 for Response (with intent prompt)"
    requirements:
      needs_intent: true 